name: cppcheck-action
on: 
 push:
   branches: [main]
 pull request: 
   branches: [main]
   
jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - name: Install cppcheck
        run: sudo apt-get  install cppcheck
      - name: Cppcheck code
        run: cppcheck --enable=all 3_Implementation 
